docker_database:
  POSTGRESQL_ADDON_HOST: localhost
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: nexttourplan
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret


clever_cloud_db:
  POSTGRESQL_ADDON_DB: br5b1cpgdywf45dq1hla
  POSTGRESQL_ADDON_HOST: br5b1cpgdywf45dq1hla-postgresql.services.clever-cloud.com
  POSTGRESQL_ADDON_PASSWORD: PN86q8SK6svMECTQ3eX8uf2gQ1s82E
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_URI: postgresql://ud40ud3jkpulmlxnk4t4:PN86q8SK6svMECTQ3eX8uf2gQ1s82E@br5b1cpgdywf45dq1hla-postgresql.services.clever-cloud.com:5432/br5b1cpgdywf45dq1hla
  POSTGRESQL_ADDON_USER: ud40ud3jkpulmlxnk4t4
  POSTGRESQL_ADDON_VERSION: 11

neon_db:
  POSTGRESQL_ADDON_DB: neondb
  POSTGRESQL_ADDON_HOST: ep-gentle-sky-364428.ap-southeast-1.aws.neon.tech
  POSTGRESQL_ADDON_PASSWORD: jfNMrAnGiF94
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_URI: postgres://mokhlesurr031@ep-gentle-sky-364428.ap-southeast-1.aws.neon.tech/neondb
  POSTGRESQL_ADDON_USER: mokhlesurr031
  POSTGRESQL_ADDON_VERSION: 15


current_db:
  RUNNING: neon_db


image_uploader_upload_io:
  BEARER_TOKEN: public_12a1xvh6D2kN8NT8fAZpvmG9sxvZ
  ACCOUNT_ID: 12a1xvh
  API_URL: https://api.upload.io/v2/accounts/12a1xvh/uploads/form_data

image_url_local:
  LOCAL_STORAGE_IMG_PATH: ./img/upload/tours/