version: '3.1'

services:

  database:
    image: postgres
    container_name: pg-tourplan
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nexttourplan
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./database:/var/lib/postgresql